name: First WorkFlow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Welcome to Github Action"
      - name: Print GoodBye
        run: echo "GoodBye"
